"""
Django settings for Selsa_project project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


from decouple import config  # Add this import at the top if not already present
PRINTFUL_API_TOKEN = config('PRINTFUL_API_TOKEN')
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n26x+iw2kk(s3_^zn&(5kr7#n(aku2-b=sx_*y&ig4tj+r5*xk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django.contrib.flatpages',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'django.contrib.admindocs',
    'django.contrib.redirects',
    'Selsa_app',
    'accounts',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'social_django',
    'django_cas_ng',
    'django_extensions',
    'invitations',
    'django.contrib.sites',  # Required for sites framework
    'pages',
    'products',
    'crispy_forms',
    'crispy_bootstrap5',  # Add this line for Bootstrap 5
    'category',
    'mptt',
    'rest_framework',
    'djangoql',
    'corsheaders',
    'adminsortable2',
    'cart',
    'orders',
    'Customers',
    'printful_sync',

]


GRAPH_MODELS = {
    'all_applications': True,
    'group_models': True,
}

# Stripe API keys

STRIPE_SECRET_KEY = 'your-secret-key'
STRIPE_PUBLISHABLE_KEY = 'your-publishable-key'



# Add this line to your settings.py file
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'  # or 'bootstrap4' if you prefer


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  #  frontend URL
]

ROOT_URLCONF = 'Selsa_project.urls'

LOGIN_URL = 'two_factor:login'
STATIC_ROOT = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "media", "images", "category_images", "product_images"),  # Project-level templates
            os.path.join(BASE_DIR, "category", "templates"),  # Project-level templates
            os.path.join(BASE_DIR, "products", "templates"),  # Project-level templates
            os.path.join(BASE_DIR, "pages", "templates"),  # Project-level templates
            os.path.join(BASE_DIR, "static", "image","js","stylesheet"),  # Project-level templates
        ],
        'APP_DIRS': True,  # Enable app-level template discovery
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



SITE_ID = 1  # Required for sites framework

INVITATIONS_INVITATION_EXPIRY = 7  # Invitation expiry in days
INVITATIONS_EMAIL_SUBJECT_PREFIX = 'Your Invitation to '
INVITATIONS_SIGNUP_REDIRECT = 'account_signup'  # URL name to redirect after accepting invitation


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static" ,
    # Add other directories containing static files if necessary
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}
WSGI_APPLICATION = 'Selsa_project.wsgi.application'

CAS_ADMIN_REDIRECT = '/admin/'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Authentication Backends

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django_cas_ng.backends.CASBackend',
    'django.contrib.auth.backends.ModelBackend',
    #'two_factor.auth_backends.TwoFactorBackend',
    
)
# Google OAuth2 Credentials

# Configure social authentication keys and secrets
# 
# Google OAuth2 Credentials
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your-google-client-id'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your-google-client-secret'

# FACEBOOK OAuth2 Credentials
SOCIAL_AUTH_FACEBOOK_KEY = 'your-facebook-app-id'
SOCIAL_AUTH_FACEBOOK_SECRET = 'your-facebook-app-secret'

# Configure CAS settings

CAS_SERVER_URL = 'https://your-cas-server/cas/'
CAS_LOGOUT_COMPLETELY = True
CAS_REDIRECT_URL = 'your-redirect-url-after-login'


LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect users after login (update as needed)
LOGOUT_REDIRECT_URL = '/login/'  # Redirect users to login page after logout


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.example.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@example.com'
EMAIL_HOST_PASSWORD = 'your_password'
"""

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}
